### PR TITLE
Fix for NullPointerException while updating hadoop job counters.

### PR DESCRIPTION
**Pull request by deepujain**
1)
Error seen in scoobi Version: 0.8.3

We have seen this error repeatedly. Even if the job succeeded with few failed map attempts, scoobi threw null pointer exception. Hence adding null checks.
Logs
===
[INFO] OutputChannel - scoobi.tmp.copy : mrename
[INFO] OutputChannel - Rename Time : 1 mins
[INFO] OutputChannel - scoobi.tmp.copy : mrename
[INFO] OutputChannel - Rename Time : 0 mins
Exception in thread "main" java.lang.NullPointerException
	at com.nicta.scoobi.impl.ScoobiConfigurationImpl.updateCounters(ScoobiConfigurationImpl.scala:99)
	at com.nicta.scoobi.impl.ScoobiConfigurationImpl.updateCounters(ScoobiConfigurationImpl.scala:45)
	at com.nicta.scoobi.impl.exec.HadoopMode$Execution$$anonfun$reportMscr$1.apply(HadoopMode.scala:173)
	at com.nicta.scoobi.impl.exec.HadoopMode$Execution$$anonfun$reportMscr$1.apply(HadoopMode.scala:171)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.nicta.scoobi.impl.exec.HadoopMode$Execution.runMscrs(HadoopMode.scala:146)
	at com.nicta.scoobi.impl.exec.HadoopMode$Execution.execute(HadoopMode.scala:125)
	at com.nicta.scoobi.impl.exec.HadoopMode$$anonfun$com$nicta$scoobi$impl$exec$HadoopMode$$executeLayer$1.apply(HadoopMode.scala:115)
	at com.nicta.scoobi.impl.exec.HadoopMode$$anonfun$com$nicta$scoobi$impl$exec$HadoopMode$$executeLayer$1.apply(HadoopMode.scala:114)
	at org.kiama.attribution.AttributionCore$CachedAttribute.apply(AttributionCore.scala:62)
	at com.nicta.scoobi.impl.exec.HadoopMode$$anonfun$com$nicta$scoobi$impl$exec$HadoopMode$$executeLayers$1$1.apply(HadoopMode.scala:73)
	at com.nicta.scoobi.impl.exec.HadoopMode$$anonfun$com$nicta$scoobi$impl$exec$HadoopMode$$executeLayers$1$1.apply(HadoopMode.scala:73)
	at scala.collection.immutable.List.foreach(List.scala:318)

Travis Build is Success = https://travis-ci.org/deepujain/scoobi

2) Updated .travis* file to include compilation and packaging.

### CODE REVIEW

**Comment by etorreborre** [comment]
Thanks for you PR. I didn't merge it in straight away because:
 - I used a more idiomatic way to use `Option` (without using `isDefined`)
 - of all the redundant `travis` commits

I have published this fix in 0.9.2-SNAPSHOT if you want to try it out.

**Comment by deepujain** [comment]
I do not see a branch/tag of 0.9.2-SNAPSHOT. How do i see your changes and which repository contains 0.9.2-SNAPSHOT jar ?

**Comment by etorreborre** [comment]
You can get it [here](https://oss.sonatype.org/content/repositories/snapshots/com/nicta/scoobi_2.11/0.9.2-SNAPSHOT/).

**Comment by deepujain** [comment]
Thanks. I will try it out. I have sent you few tweets regarding the help i need in setting up my scala project on eclipse. Could you please help me out there.

**Comment by deepujain** [comment]
Can snapshot be used with 2.10 scala version ?

We use.
<scala.version>2.10.3</scala.version>
<scala.binary.version>2.10</scala.binary.version>
<scala.tools.version>2.10</scala.tools.version>

**Comment by etorreborre** [comment]
Can you bring that to the [mailing-list](https://groups.google.com/forum/#!forum/scoobi-users)? I am not a Eclipse user but maybe other people can help you out there.

**Comment by etorreborre** [comment]
I have now published a Scoobi version for Scala 2.10: https://oss.sonatype.org/content/repositories/snapshots/com/nicta/scoobi_2.10/0.9.2-SNAPSHOT/

**Pull request closed without merging**
